version: '3.4'

services:
  alertsystem:
    image: alertsystem
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - 5002:5002
    environment:
      - DATABASE_URL=value
    depends_on:
      - db
  db:
    image: db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./data_import:/data_import
    ports:
      - 5432:5432
volumes:
  data_import: