version: '3.4'

services:
  alertsystem:
    image: alertsystem
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - 5002:5002
    environment:
      - DATABASE_URL=value
    depends_on:
      - db
  db:
    image: db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./data_import:/data_import
    ports:
      - 5432:5432
  data_processing:
    image: processing
    build: 
      context: .
      dockerfile: ./Dockerfile.processing
    tty: true 
    depends_on:
      - db 
  data_import:
    image: osgeo/gdal
    depends_on:
      - db
    volumes: 
      - ./data_import:/data_import
    command: bash -c "sleep 7 && /data_import/import.sh"
  address_ogc_service:
    image: camptocamp/mapserver
    environment:
      - MS_DEBUGLEVEL=5
      # - LISTEN_PORT_80=1
    volumes:
      - /mapfiles/address.map/:/etc/mapserver/address.map:ro
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  data_import: